<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVb3axhc\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVb3axhc/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerVb3axhc.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerVb3axhc\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerVb3axhc\appProdProjectContainer([
    'container.build_hash' => 'Vb3axhc',
    'container.build_id' => 'e9751dfe',
    'container.build_time' => 1571082887,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVb3axhc');
